services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dailylog_dev_app
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: dailylog_dev_redis
    restart: unless-stopped
    volumes:
      - redis_dev_data:/data

volumes:
  redis_dev_data:
