services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dailylog_prod_app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOGIN_TOKEN=***.env
      - REDIS_HOST=redis
      - SERVER_NAME=:80
      - FRANKENPHP_WORKER=public/index.php
      - FRANKENPHP_MAX_REQUESTS=500
      - DB_CONNECTION=pgsql
      - DB_HOST=aws-1-ap-southeast-1.pooler.supabase.com
      - DB_PORT=6543
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres.kwnittytkysgncapkghw
      - DB_PASSWORD=***
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: dailylog_prod_redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_prod_data:/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: dailylog_prod_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=***
    depends_on:
      - app

volumes:
  redis_prod_data:
